Log=ERROR
#Syslog=DEBUG
Stdout=DEBUG
[com]
port_name=/dev/ttyUSB1
port_speed=115200
[log]
log_folder=log
log_rotation=1
[remote]
server_list=172.17.31.144
server_port=6802
[sql]
server=localhost
username=root
password=lab4man1
database=msg_dumper
[syslog]
facility_name=daemon
[stdout]
# 0: _IONBF	no buffering	不使用 buffer，每次 I/O 都直接 write()
# 1: _IOLBF	line buffering	遇到 \n 就 flush
# 2: _IOFBF	full buffering	buffer 滿才 flush
normal_output=1
error_output=0

